# Input/output configuration
data_dir: /data/FNAL/events
super_dir: /data/FNAL/processed
#super_dir: /data/FNAL/supergraphs

# Dataset parameters
datatype_names: [train, val, test] # Which directory prefixes to use, assuming at least a train dataset 
train_split: [300, 10, 10] # Number of [training, validation, testing] examples
test_split: [5, 1, 1]

# Definition of reconstructable particles
ptcut: 1.0 
n_hits: 5 
primary: False

# Weighting training samples by 
# w = weight_min + (1 - weight_min)*min(max(pt - pt_cut + pt_interval, 0), 1) + weight_leak*max(pt - ptcut, 0)
weight_leak: 1.0 
weight_min: 0.5
pt_interval: 0.5

# Data filtering
noise: True # Include noise hits or not
hard_ptcut: 0 # Introduce hard background cut or not; 0 means keep everything
edge_dropping_ratio: 0. # Randomly removing edges; 0 means keep all edges
remove_isolated: False # Remove disconnected singlets; this won't affect track evaluation  

# Track Candidate Selection
score_cut: 0.7 

# Model parameters
model: BC-HGNN-GMM
spatial_channels: 3 
latent: 256 # size of node & edge representations
hidden: ratio # size of hidden layers; ratio means using hidden_ratio*latent
hidden_ratio: 2
emb_dim: 8 # Dimensionality of intermediate embedding space

# Number of iterations
n_interaction_graph_iters: 6 
n_hierarchical_graph_iters: 6

# Depth of networks
nb_node_layer: 3 
nb_edge_layer: 2
output_layers: 3

# Other Network Specification
hidden_output_activation: Tanh
hidden_activation: GELU
layernorm: True
share_weight: False

# Loss Specification
train_r: 1.0
log_weight_ratio: 0 # ln(positive_sample_weight) - ln(negative_sample_weight)

# Optimizer 
warmup: 100
lr: 0.001
factor: 0.99
patience: 1
max_epochs: 200 #500
emb_epoch: 100

# Hierarchical Structure Construction
bipartitegraph_sparsity: 5
supergraph_sparsity: 5 #10
min_cluster_size: 3
cluster_granularity: 3 #5

# Track evaluation
majority_cut: 0.5
