wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: true
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.8.13
    start_time: 1667688985
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 54
      - 55
      3:
      - 7
      - 23
      4: 3.8.13
      5: 0.12.16
      8:
      - 1
      - 2
      - 5
cell_channels:
  desc: null
  value: 8
checkpointing:
  desc: null
  value: true
cluster_granularity:
  desc: null
  value: 0
datatype_names:
  desc: null
  value:
  - train
  - val
  - test
detector_width:
  desc: null
  value: 2
edge_dropping_ratio:
  desc: null
  value: 0.0
emb_dim:
  desc: null
  value: 8
factor:
  desc: null
  value: 0.99
hard_ptcut:
  desc: null
  value: 0
hidden:
  desc: null
  value: 256
hidden_activation:
  desc: null
  value: GELU
hidden_output_activation:
  desc: null
  value: Tanh
hidden_ratio:
  desc: null
  value: 2
input_dir:
  desc: null
  value: /global/cfs/cdirs/m3443/usr/ryanliu/TrackML_data/filter_processed/
knn:
  desc: null
  value: 100
latent:
  desc: null
  value: 128
layernorm:
  desc: null
  value: true
log_weight_ratio:
  desc: null
  value: 0
lr:
  desc: null
  value: 0.001
majority_cut:
  desc: null
  value: 0.5
max_epochs:
  desc: null
  value: 300
max_r:
  desc: null
  value: 5
min_r:
  desc: null
  value: 1
model:
  desc: null
  value: EC-IN
n_hits:
  desc: null
  value: 5
n_pure_interaction_graph_iters:
  desc: null
  value: 14
nb_edge_layer:
  desc: null
  value: 2
nb_node_layer:
  desc: null
  value: 3
noise:
  desc: null
  value: true
num_layers:
  desc: null
  value: 10
num_tracks:
  desc: null
  value: 200
output_layers:
  desc: null
  value: 3
patience:
  desc: null
  value: 1
primary:
  desc: null
  value: false
pt_interval:
  desc: null
  value: 0.5
ptcut:
  desc: null
  value: 1.0
regime:
  desc: null
  value: []
remove_isolated:
  desc: null
  value: false
score_cut:
  desc: null
  value: 0.7
share_weight:
  desc: null
  value: false
spatial_channels:
  desc: null
  value: 3
toy_eff:
  desc: null
  value: 0.9
toy_pur:
  desc: null
  value: 0.5
track_dis_width:
  desc: null
  value: 10
train_r:
  desc: null
  value: 1.0
train_split:
  desc: null
  value:
  - 2000
  - 100
  - 100
true_edges:
  desc: null
  value: pid_true_edges
use_toy:
  desc: null
  value: false
warmup:
  desc: null
  value: 100
weight_leak:
  desc: null
  value: 1.0
weight_min:
  desc: null
  value: 0.5
