wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: true
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.8.13
    start_time: 1667691941
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 54
      - 55
      3:
      - 7
      - 23
      4: 3.8.13
      5: 0.12.16
      8:
      - 1
      - 2
      - 5
bipartitegraph_sparsity:
  desc: null
  value: 8
cluster_granularity:
  desc: null
  value: 3
datatype_names:
  desc: null
  value:
  - train
  - val
  - test
edge_dropping_ratio:
  desc: null
  value: 0.0
emb_dim:
  desc: null
  value: 8
emb_epoch:
  desc: null
  value: 30
factor:
  desc: null
  value: 0.98
hard_ptcut:
  desc: null
  value: 0
hidden:
  desc: null
  value: 256
hidden_activation:
  desc: null
  value: GELU
hidden_output_activation:
  desc: null
  value: GELU
hidden_ratio:
  desc: null
  value: 2
inference_min_cluster_size:
  desc: null
  value: 5
input_dir:
  desc: null
  value: /global/cfs/cdirs/m3443/usr/ryanliu/TrackML_data/filter_processed/
knn:
  desc: null
  value: 100
latent:
  desc: null
  value: 128
layernorm:
  desc: null
  value: true
log_weight_ratio:
  desc: null
  value: 0
lr:
  desc: null
  value: 0.001
majority_cut:
  desc: null
  value: 0.5
max_epochs:
  desc: null
  value: 200
min_cluster_size:
  desc: null
  value: 3
model:
  desc: null
  value: BC-HGNN-GMM
n_hierarchical_graph_iters:
  desc: null
  value: 8
n_hits:
  desc: null
  value: 5
n_interaction_graph_iters:
  desc: null
  value: 6
nb_edge_layer:
  desc: null
  value: 2
nb_node_layer:
  desc: null
  value: 3
noise:
  desc: null
  value: true
output_layers:
  desc: null
  value: 3
patience:
  desc: null
  value: 1
primary:
  desc: null
  value: false
pt_interval:
  desc: null
  value: 0.5
ptcut:
  desc: null
  value: 1.0
remove_isolated:
  desc: null
  value: true
share_weight:
  desc: null
  value: false
spatial_channels:
  desc: null
  value: 3
supergraph_sparsity:
  desc: null
  value: 10
train_r:
  desc: null
  value: 1.0
train_split:
  desc: null
  value:
  - 2000
  - 100
  - 100
true_edges:
  desc: null
  value: modulewise_true_edges
warmup:
  desc: null
  value: 100
weight_leak:
  desc: null
  value: 1.0
weight_min:
  desc: null
  value: 0.5
